//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.VisualStudio.ServiceReference.Platforms, version 15.0.26323.1
// 
namespace mVozac.ServiceReference2
{
    using System;
    using System.Runtime.Serialization;
    using System.Threading.Tasks;

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "CompositeType", Namespace = "http://schemas.datacontract.org/2004/07/WcfToDB")]
    public partial class CompositeType : object, System.ComponentModel.INotifyPropertyChanged
    {

        private bool BoolValueField;

        private string StringValueField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue
        {
            get
            {
                return this.BoolValueField;
            }
            set
            {
                if ((this.BoolValueField.Equals(value) != true))
                {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue
        {
            get
            {
                return this.StringValueField;
            }
            set
            {
                if ((object.ReferenceEquals(this.StringValueField, value) != true))
                {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Korisnik", Namespace = "http://schemas.datacontract.org/2004/07/WcfToDB")]
    public partial class Korisnik : object, System.ComponentModel.INotifyPropertyChanged
    {

        private System.DateTime DatumRodenjaField;

        private string EmailField;

        private string ImeField;

        private string KorisnickoImeField;

        private string LozinkaField;

        private string OIBField;

        private string PrezimeField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumRodenja
        {
            get
            {
                return this.DatumRodenjaField;
            }
            set
            {
                if ((this.DatumRodenjaField.Equals(value) != true))
                {
                    this.DatumRodenjaField = value;
                    this.RaisePropertyChanged("DatumRodenja");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email
        {
            get
            {
                return this.EmailField;
            }
            set
            {
                if ((object.ReferenceEquals(this.EmailField, value) != true))
                {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Ime
        {
            get
            {
                return this.ImeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ImeField, value) != true))
                {
                    this.ImeField = value;
                    this.RaisePropertyChanged("Ime");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KorisnickoIme
        {
            get
            {
                return this.KorisnickoImeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.KorisnickoImeField, value) != true))
                {
                    this.KorisnickoImeField = value;
                    this.RaisePropertyChanged("KorisnickoIme");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Lozinka
        {
            get
            {
                return this.LozinkaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.LozinkaField, value) != true))
                {
                    this.LozinkaField = value;
                    this.RaisePropertyChanged("Lozinka");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OIB
        {
            get
            {
                return this.OIBField;
            }
            set
            {
                if ((object.ReferenceEquals(this.OIBField, value) != true))
                {
                    this.OIBField = value;
                    this.RaisePropertyChanged("OIB");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Prezime
        {
            get
            {
                return this.PrezimeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PrezimeField, value) != true))
                {
                    this.PrezimeField = value;
                    this.RaisePropertyChanged("Prezime");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name = "Voznja", Namespace = "http://schemas.datacontract.org/2004/07/WcfToDB")]
    public partial class Voznja : object, System.ComponentModel.INotifyPropertyChanged
    {

        private int BrojSjedalaField;

        private System.DateTime DatumVoznjeField;

        private string ImeVozacaField;

        private string NazivLinijeField;

        private string PrezimeVozacaField;

        [System.Runtime.Serialization.DataMemberAttribute()]
        public int BrojSjedala
        {
            get
            {
                return this.BrojSjedalaField;
            }
            set
            {
                if ((this.BrojSjedalaField.Equals(value) != true))
                {
                    this.BrojSjedalaField = value;
                    this.RaisePropertyChanged("BrojSjedala");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DatumVoznje
        {
            get
            {
                return this.DatumVoznjeField;
            }
            set
            {
                if ((this.DatumVoznjeField.Equals(value) != true))
                {
                    this.DatumVoznjeField = value;
                    this.RaisePropertyChanged("DatumVoznje");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ImeVozaca
        {
            get
            {
                return this.ImeVozacaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.ImeVozacaField, value) != true))
                {
                    this.ImeVozacaField = value;
                    this.RaisePropertyChanged("ImeVozaca");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NazivLinije
        {
            get
            {
                return this.NazivLinijeField;
            }
            set
            {
                if ((object.ReferenceEquals(this.NazivLinijeField, value) != true))
                {
                    this.NazivLinijeField = value;
                    this.RaisePropertyChanged("NazivLinije");
                }
            }
        }

        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PrezimeVozaca
        {
            get
            {
                return this.PrezimeVozacaField;
            }
            set
            {
                if ((object.ReferenceEquals(this.PrezimeVozacaField, value) != true))
                {
                    this.PrezimeVozacaField = value;
                    this.RaisePropertyChanged("PrezimeVozaca");
                }
            }
        }

        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

        protected void RaisePropertyChanged(string propertyName)
        {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null))
            {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName = "ServiceReference2.IService1")]
    public interface IService1
    {

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/GetData", ReplyAction = "http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction = "http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<mVozac.ServiceReference2.CompositeType> GetDataUsingDataContractAsync(mVozac.ServiceReference2.CompositeType composite);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/InsertKorisnika", ReplyAction = "http://tempuri.org/IService1/InsertKorisnikaResponse")]
        System.Threading.Tasks.Task<int> InsertKorisnikaAsync(mVozac.ServiceReference2.Korisnik k);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/SelectKorisnika", ReplyAction = "http://tempuri.org/IService1/SelectKorisnikaResponse")]
        System.Threading.Tasks.Task<mVozac.ServiceReference2.Korisnik> SelectKorisnikaAsync(mVozac.ServiceReference2.Korisnik k);

        [System.ServiceModel.OperationContractAttribute(Action = "http://tempuri.org/IService1/SelectVoznju", ReplyAction = "http://tempuri.org/IService1/SelectVoznjuResponse")]
        System.Threading.Tasks.Task<mVozac.ServiceReference2.Voznja> SelectVoznjuAsync(string tekst);
    }

    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : mVozac.ServiceReference2.IService1, System.ServiceModel.IClientChannel
    {
    }

    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<mVozac.ServiceReference2.IService1>, mVozac.ServiceReference2.IService1
    {

        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);

        public Service1Client() :
                base(Service1Client.GetDefaultBinding(), Service1Client.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IService1.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public Service1Client(EndpointConfiguration endpointConfiguration) :
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), Service1Client.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public Service1Client(EndpointConfiguration endpointConfiguration, string remoteAddress) :
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public Service1Client(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) :
                base(Service1Client.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }

        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) :
                base(binding, remoteAddress)
        {
        }

        public System.Threading.Tasks.Task<string> GetDataAsync(int value)
        {
            return base.Channel.GetDataAsync(value);
        }

        public System.Threading.Tasks.Task<mVozac.ServiceReference2.CompositeType> GetDataUsingDataContractAsync(mVozac.ServiceReference2.CompositeType composite)
        {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }

        public System.Threading.Tasks.Task<int> InsertKorisnikaAsync(mVozac.ServiceReference2.Korisnik k)
        {
            return base.Channel.InsertKorisnikaAsync(k);
        }

        public System.Threading.Tasks.Task<mVozac.ServiceReference2.Korisnik> SelectKorisnikaAsync(mVozac.ServiceReference2.Korisnik k)
        {
            return base.Channel.SelectKorisnikaAsync(k);
        }

        public System.Threading.Tasks.Task<mVozac.ServiceReference2.Voznja> SelectVoznjuAsync(string tekst)
        {
            return base.Channel.SelectVoznjuAsync(tekst);
        }

        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }

        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }

        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IService1))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:8733/Design_Time_Addresses/WcfToDB/Service1/");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }

        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Service1Client.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IService1);
        }

        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Service1Client.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IService1);
        }

        public enum EndpointConfiguration
        {

            BasicHttpBinding_IService1,
        }
    }
}
